package ptr

// DO NOT MODIFY. Generated by ptr-generate.

import (
	{{range .Imports -}}
	"{{.}}"
	{{- end}}
)

// {{.Method}} returns a pointer to {{.Indefinite}} {{.NativeType}}.
func {{.Method}}({{.Var}} {{.NativeType}}) *{{.NativeType}} {
	return &{{.Var}}
}
