package ptr

// DO NOT MODIFY. Generated by ptr-generate.

{{ if .Imports -}}
import (
	{{range .Imports -}}
	"{{.}}"
	{{- end}}
)
{{- end}}

// {{.Method}} returns a pointer to {{.Indefinite}} {{.NativeType}}.
func {{.Method}}({{.Var}} {{.NativeType}}) *{{.NativeType}} {
	return &{{.Var}}
}
