package ptr_test

// Do not modify. Generated by nullable-generate.

import (
	"fmt"
	"testing"

	"github.com/spkg/ptr"
	"github.com/spkg/ptr/deref"
)

func TestString(t *testing.T) {
	tests := []struct {
		Value string
	}{
		{
			Value: "string-val",
		},
		{
			Value: "",
		},
	}
	for i, tt := range tests {
		ttName := fmt.Sprintf("test %d", i)
		p := ptr.String(tt.Value)
		v := deref.String(p)
		if tt.Value != v {
			t.Errorf("%s: expected=%v, actual=%v", ttName, tt.Value, v)
		}
	}
}
