package ptr_test

// Do not modify. Generated by nullable-generate.

import (
	"fmt"
	"github.com/spkg/ptr"
	"github.com/spkg/ptr/deref"
	"testing"
	"time"
)

func TestTime(t *testing.T) {
	tests := []struct {
		Value time.Time
	}{
		{
			Value: time.Date(2001, 11, 10, 15, 04, 05, 0, time.FixedZone("AEST", 10*3600)),
		},
		{
			Value: time.Time{},
		},
	}
	for i, tt := range tests {
		ttName := fmt.Sprintf("test %d", i)
		p := ptr.Time(tt.Value)
		v := deref.Time(p)
		if !tt.Value.Equal(v) {
			t.Errorf("%s: expected=%v, actual=%v", ttName, tt.Value, v)
		}
	}
}
