package deref

// DO NOT MODIFY. Generated by nullable-generate.

import ()

// Bool returns the value pointed to by bp.
// If bp is nil, then this function returns false.
func Bool(bp *bool) bool {
	if bp == nil {
		return false
	}
	return *bp
}
