package deref

// DO NOT MODIFY. Generated by nullable-generate.

// Float32 returns the value pointed to by np.
// If np is nil, then this function returns 0.
func Float32(np *float32) float32 {
	if np == nil {
		return 0
	}
	return *np
}
