package deref

// DO NOT MODIFY. Generated by nullable-generate.

import ()

// Float64 returns the value pointed to by np.
// If np is nil, then this function returns 0.
func Float64(np *float64) float64 {
	if np == nil {
		return 0
	}
	return *np
}
