package deref

// DO NOT MODIFY. Generated by nullable-generate.

import ()

// Int returns the value pointed to by np.
// If np is nil, then this function returns 0.
func Int(np *int) int {
	if np == nil {
		return 0
	}
	return *np
}
