package deref

// DO NOT MODIFY. Generated by nullable-generate.

// Int16 returns the value pointed to by np.
// If np is nil, then this function returns 0.
func Int16(np *int16) int16 {
	if np == nil {
		return 0
	}
	return *np
}
