package deref

// DO NOT MODIFY. Generated by nullable-generate.

import ()

// Int32 returns the value pointed to by np.
// If np is nil, then this function returns 0.
func Int32(np *int32) int32 {
	if np == nil {
		return 0
	}
	return *np
}
