package deref

// DO NOT MODIFY. Generated by nullable-generate.

// Int64 returns the value pointed to by np.
// If np is nil, then this function returns 0.
func Int64(np *int64) int64 {
	if np == nil {
		return 0
	}
	return *np
}
