package deref

// DO NOT MODIFY. Generated by nullable-generate.

// Int8 returns the value pointed to by np.
// If np is nil, then this function returns 0.
func Int8(np *int8) int8 {
	if np == nil {
		return 0
	}
	return *np
}
