package deref

// DO NOT MODIFY. Generated by nullable-generate.

import (
	"time"
)

// Time returns the value pointed to by tp.
// If tp is nil, then this function returns time.Time{}.
func Time(tp *time.Time) time.Time {
	if tp == nil {
		return time.Time{}
	}
	return *tp
}
